yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied_view'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField('text_comments')
    created = models.DateTimeField(
        'date_comments',
        auto_now_add=True
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Comments'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'Follow'

    def __str__(self):
        return (f'Пользователь {self.user} '
                f'подписан на пользователя {self.author}'
                )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {"text": "Подсказка"}
        labels = {
            'text': ('текст'),
            'group': ('группа'),
            'help_text': ('подсказка')
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {
            'text': 'Напишите свой комментарий к посту'
        }

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render


from .forms import PostForm, CommentForm
from .models import Group, Post, User, Comment, Follow


def index(request):
    posts = Post.objects.order_by('-pub_date')
    paginator = Paginator(posts, settings.PAGINATOR_OBJECTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.order_by('-pub_date')
    paginator = Paginator(posts, settings.PAGINATOR_OBJECTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    post_list = author.posts.order_by('-pub_date')
    post_count = post_list.count
    paginator = Paginator(post_list, settings.PAGINATOR_OBJECTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=author).exists()
    context = {
        'page_obj': page_obj,
        'username': author,
        'paginator': paginator,
        'post_count': post_count,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment = Comment.objects.select_related("post").filter(post=post)
    form = CommentForm(request.POST or None)
    author_name = post.author
    context = {
        'form': form,
        'post': post,
        'author_name': author_name,
        'comment': comment

    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def add_comment(request, post_id):
    post = Post.objects.get(pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()

    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.select_related('author', 'group').filter(
        author__following__user=request.user)
    paginator = Paginator(posts, settings.PAGINATOR_OBJECTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(user=request.user, author=author)
    if follow.exists():
        follow.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}

{% if form.instance.pk %} Редактировать запись
{% else %}  Добавить запись {% endif %}

{%endblock%}

{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        {% if form.instance.pk %} Редактировать пост
                        {% else %} Создать новый пост {% endif %}
                    </div>
                    {% include 'includes/forms_error.html' %}
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data" action="{% if form.instance.pk %}
                        {% url 'posts:post_edit' form.instance.pk %}
    {% else %}{% url 'posts:post_create' %}{% endif %}">
                            {% csrf_token %}
                            {% include 'includes/for_field_in_form.html' %}
                            <div class="d-flex justify-content-end">
                                <button type="submit"
                                        class="btn btn-primary">
                                    {% if form.instance.pk %} Изменить
                                    {% else %} Сохранить {% endif %}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Вы подписаны на авторов{% endblock %}

  {% block content %}
    <div class="container py-5">     
      <h1>Посты авторов, на которых вы подписаны </h1>
      <article>
        {% include 'posts/includes/switcher.html' %}
        {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% load thumbnail %}
        {% thumbnail post.image "960x339" crop="left" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        {% if post.group %}   
          <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
        {% endif %} 
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      </article>
      {% include 'posts/includes/paginator.html' %}
    </div> 
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  Записи сообщества {{group.title}}
{% endblock title %}

{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{group.description|linebreaksbr}}</p>
  {% for post in  page_obj %}
    {% include 'posts/includes/post_card.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% cache 20 index_page %}

{% block title %}
Последние обновления на сайте
{% endblock title %}

{% block content %}
    <div class="container py-5">     
      <h1>Последние обновления на сайте</h1>
      <article>
        {% include 'posts/includes/switcher.html' %}
        {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% load thumbnail %}
        {% thumbnail post.image "960x339" crop="left" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        {% if post.group %}   
          <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
        {% endif %} 
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      </article>
      {% include 'posts/includes/paginator.html' %}
    </div> 
{% endblock content %}
{% endcache %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}

{% block title %}
    Пост {{ post.text|truncatechars:30 }}
{% endblock %}

{% block content%}
    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                     Дата публикации: {{post.pub_date|date:"j E Y"}}
                </li>
                    {% if post.group %}
                <li class="list-group-item">
                    Группа: <a
                        href="{% url 'posts:group_posts' post.group.slug %}">
                    {{ post.group }}</a>
                </li>
                    {% else %}
                <span style="color: black">
                <li class="list-group-item">
                    Этой публикации нет ни в одном сообществе.</span>
                </li>    
                    {% endif %}
                <li class="list-group-item">
                    Автор:
                    <a href="{% url 'posts:profile' post.author.username %}">
                        {{ post.author.get_full_name }} все посты</a>
                </li>
                <li class="list-group-item d-flex justify-content-between
                align-items-center">
                    Всего постов автора:
                    <span> {{ post.author.posts.count }}</span>
                </li>
            </ul>
        </aside>
        <article class="col-12 col-md-9">
            {% thumbnail post.image "960x339" crop="left" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>
                {{ post.text|linebreaks }}
            </p>
            {% if user == post.author %}
                <a class="btn btn-primary"
                href="{% url 'posts:post_edit' post.pk %}">
                Редактировать запись
            </a>
            {% endif %}
            {% load user_filters %}
            {% if user.is_authenticated %}
              <div class="card my-4">
                <h5 class="card-header">Добавить комментарий:</h5>
                <div class="card-body">
                  <form method="post" action="{% url 'posts:add_comment' post.id %}">
                    {% csrf_token %}      
                    <div class="form-group mb-2">
                      {{ form.text }}
                    </div>
                    <button type="submit" class="btn btn-primary">Отправить</button>
                  </form>
                </div>
              </div>
            {% endif %}
            
            {% for comments in comment %}
              <div class="media mb-4">
                <div class="media-body">
                  <h5 class="mt-0">
                    <a href="{% url 'posts:profile' comments.author.username %}">
                      {{ comments.author.username }}
                    </a>
                  </h5>
                    <p>
                     {{ comments.text }}
                    </p>
                  </div>
                </div>
            {% endfor %} 
        </article>
    </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Профайл пользователя {{ username.get_full_name }}
{% endblock %}
{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{ username.get_full_name }} </h1>
    <h3>Всего постов: {{ username.posts.count }} </h3>
    {% if request.user != username %}
      {% if following %}
        <a 
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a 
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}
    {% for post in page_obj %}
      <article>
        <ul>
        <li>
          Автор: {{ username.get_full_name }}
          <a href="{% url 'posts:profile' post.author.get_username %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        </ul>
        {% thumbnail post.image "960x339" crop="left" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post_id=post.pk %}">подробная информация </a>
      </article>       
      {% if post.group %}
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
      {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %} 
  </div>
{% endblock %}